### ISSUE TITLE
Issue with auth/callback Routing

### ISSUE THREAD

**Issue by tmmocha** [donatmarko/ivao-booking#180]
For using Oauth2 from IVAO login, the routing `Route::get('auth/callback','AuthIvaoController@callback');` is not working.

For now, you can bypass this method by creating `index.php` as `auth/callback/index.php`

@donatmarko, please check the route function, which is not working. Thank you

```
<?php 
if (isset($_GET['code']) && isset($_GET['state'])) {
    header('Location: ../../newlogin_ivao.php?code='. $_GET['code'] . '&state=' . $_GET['state']);
} else {
    header('Location: ../../newlogin_ivao.php');
}

**Comment by donatmarko** [comment]
problem bypassed for now on, needs to be revisited at a bigger overhaul
